sonar.projectKey=go-sample-app
sonar.organization=codit04_Voice-Assistant-with-python

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Voice-Assistant-with-python
sonar.projectVersion=1.0


sonar.externalIssuesReportPaths=report.json
